global:
  scrape_interval: 15s
  evaluation_interval: 15s

# scrape_configs:
#   # Scrape metrics from each service
#   - job_name: 'frontend'
#     static_configs:
#       - targets: ['frontend:9100']
  
#   - job_name: 'api-layer'
#     static_configs:
#       - targets: ['api-layer:9100']
scrape_configs:
  - job_name: 'model1'
    static_configs:
      - targets: ['model1:9100']  # debug: change to localhost:9100 ?
  
  - job_name: 'generate_new_products'
    static_configs:
      - targets: ['generate_new_products:9101']  

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9102']
