global:
  scrape_interval: 15s
  evaluation_interval: 15s

# scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9100']

#   # Scrape metrics from each service
#   - job_name: 'frontend'
#     static_configs:
#       - targets: ['frontend:9101']
  
#   - job_name: 'api-layer'
#     static_configs:
#       - targets: ['api-layer:9102']
scrape_configs:
  - job_name: 'model_1'
    static_configs:
      - targets: ['model_1:9103'] 
# TODO: Have models 2-4 have targets 9104-9106 ?
  
  - job_name: 'generate_new_products'
    static_configs:
      - targets: ['generate_new_products:9107']  
