apiVersion: v1
kind: Service
metadata:
  name: model-1-service
  labels:
    app: model-1
spec:
  selector:
    app: model-1
  ports:
  - name: http
    protocol: TCP
    port: 5003
    targetPort: 5003
  - name: metrics
    protocol: TCP
    port: 9103
    targetPort: 9103
  type: ClusterIP
